### ISSUE TITLE
Commandline Options Request

### ISSUE THREAD

**Issue by SaschaVasarrhelyi** [dreamer/roberta#10]
Hi i write here because i don't mind how it works to set an commandlineoption to start the game directly without to came first to the gamelist of scummvm. Like the startparameter "sky" if i start Beneath a steel sky from the console with scummvm for example: "scummvm sky" to start the game directly. I have try many things but i could'nd bring this to work with the startparameters in steam and roberta. Is there a option i can set to roberta to bring the game to start directly or is that something you could add?

**Comment by dreamer** [comment]
@SaschaVasarrhelyi There's `LUX_SCUMMVM_CMD` environment variable: https://github.com/dreamer/roberta#configuration - you can use it to change ScummVM command line per-game.

To quote documentation in README:

> Additionally, per-game settings can be changed through variables set in Steam client. For example, to force game to use your secondary screen, right-click your game in Steam Library, select Properties → Set Launch Options… and set: (…)

    LUX_SCUMMVM_CMD="scummvm sky" %command%.

This *should* work. I'll double-check if it actually works in few minutes.

*edit* It does not work - whenever I use both launching of specific game and ScummVM `-p` parameter, ScummVM hangs on start. Also LUX_SCUMMVM_CMD does not allow for appending parameters to the end of command, which is needed for passing the game parameter.

**Comment by dreamer** [comment]
@SaschaVasarrhelyi OK, I have test fix ready - please try this build: [roberta.zip](https://github.com/dreamer/roberta/files/6176182/roberta.zip) and following Launch Options:

    LUX_SCUMMVM_GAME=sky %command%

Confirm if it works, please.

**Comment by SaschaVasarrhelyi** [comment]
Hi, thank you verry much. The second command are working with the build you send me. :)
