### ISSUE TITLE
Engine Request: ResidualVM

### ISSUE THREAD

**Issue by mindcombatant** [dreamer/roberta#2]
Just putting this here as a potential todo. ResidualVM is pretty similar to ScummVM, just with different engines, to my understanding, so it feels like it should be done in this project. I'd be able to test with Myst 3 and The Longest Journey, or provide details on the file structure of the Steam versions of those games if needed,

**Comment by dreamer** [comment]
It is definitely on the roadmap for 0.2.0 :) I need to investigate if game detection works the same way as in ScummVM (I think it does, but I haven't checked it) and get access to games that can be tested with it (we are documenting both ScummVM and ResidualVM games on [curator page](https://store.steampowered.com/curator/35667778-Powered-by-ScummVM/)).

Also, ResidualVM is [missing from repositories on many distributions](https://repology.org/project/residualvm/versions), so even before 0.2.0 we need to spread some requests to make it available to more users.

**Comment by ghost** [comment]
There's only one or two games that are likely to work with ResidualVM, I would put this on low priority.

**Comment by gimavi** [comment]
The Longest Journey [should now be in good shape](https://www.residualvm.org/news/20191110/) with ResidualVM.

If adding support is on the roadmap, can we agree on a refactoring strategy to accommodate both VMs?

**Comment by dreamer** [comment]
As long as ResidualVM has the same game detection capabilities as ScummVM, handling both should rather straightforward :)

**Comment by gimavi** [comment]
It does! The current detect_games() function should work exactly the same, as running the command manually achieves the same result and works fine with TLJ. It also adds a [residualvm] section to the configuration file, followed by game sections ([tlj-win] in this case), so the count_detected_games() function should also work just fine. Only problem is: if the file doesn't exist, and we let ResidualVM create it, it won't contain a [scummvm] section, and the counting function will abort the program upon trying to remove that string from the list of sections, so we'll first need to check whether a game is detectable by each VM separately, or add a check for the presence of "scummvm"/"residualvm" in the list.

**Comment by neuromancer** [comment]
ResidualVM was merged with scummvm, so this feature should not require anything special, just compile a recent scummvm version and run games like TLJ.

**Comment by dreamer** [comment]
Oh, it's a recent development: https://www.scummvm.org/news/20201009/ - great news, thanks @neuromancer :)

I guess it will be released in ScummVM 2.3.0 - we'll see. Closing this request.
