### ISSUE TITLE
added roberta support in my steamtinkerlaunch wrapper script

### ISSUE THREAD

**Issue by frostworx** [dreamer/roberta#9]
Hi,
just wanted to let you know that I added roberta support in v1.0.3 of my linux wrapper script steamtinkerlaunch (or short stl)
https://github.com/frostworx/steamtinkerlaunch
Either enabled inside the gameconfig or simply add a game to the steam category ScummVM to automatically start it with roberta.
Also planning to add luxtorpeda  support.
boxtron support was already added in v1.0.2 :) :
https://github.com/dreamer/boxtron/issues/40

Sorry if it is inappropriate to open a issue for this!

**Comment by ghost** [comment]
Can you also try to support luxtorpeda-dev?
https://github.com/luxtorpeda-dev/luxtorpeda

**Comment by frostworx** [comment]
I'm pretty sure it works ootb, because it probably has the same command line arguments.
If not I'll try to make the required changes.

**Comment by frostworx** [comment]
just gave it a quick try with Morrowind:
it initially failed with
`Error: Custom { kind: Other, error: "choices with no engine choice picked" }`
but after running it once without stl it popped up a selector for openmw or openmw-launcher, installed some qt stuff and afterwards it worked with stl. I'm afraid there's nothing I can do if it doesn't work ootb, the start %command% is identical in both versions.
